spring:
  application:
    name: todo-app
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      add-mappings: false
server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    defaultModelsExpandDepth: 0
    operations-sorter: alpha

  api-docs:
    path: /v3/api-docs
    enabled: true

